# Generated by Django 5.2.18 on 2026-10-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_cambio_venta_motivo_anulacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
