import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Eye, PackagePlus, Search, SlidersHorizontal } from 'lucide-react';
import { Badge, Button, Drawer, EmptyState, Input, Pagination, Select, Skeleton } from '@/components/ui/Primitives';
import { useToast } from '@/components/ui/ToastContext';
import { useAppStore } from '@/store/appStore';
import { inventarioApi, type Producto } from './api';

const productoSchema = z.object({ referencia: z.string().trim().min(1, 'Ingresa la referencia'), nombre: z.string().trim().min(1, 'Ingresa el nombre'), categoria: z.string(), precio_venta: z.coerce.number().min(0), stock_minimo: z.coerce.number().min(0) });
const categoriaSchema = z.object({ nombre: z.string().trim().min(1, 'Escribe el nombre de la categoría').max(100, 'Máximo 100 caracteres') });
type ProductoForm = z.infer<typeof productoSchema>;
const cop = new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 });

export default function Inventario() {
  const user = useAppStore(s => s.user);
  const [search, setSearch] = useState('');
  const [estado, setEstado] = useState('');
  const [categoria, setCategoria] = useState('');
  const [page, setPage] = useState(1);
  const [edit, setEdit] = useState<Producto | null | undefined>(undefined);
  const [categoryOpen, setCategoryOpen] = useState(false);
  const [selected, setSelected] = useState<Producto | null>(null);
  const [adjust, setAdjust] = useState<Producto | null>(null);
  const [adjustForm, setAdjustForm] = useState({ cantidad: '', direccion: 'ENTRADA', motivo: '' });
  const qc = useQueryClient(); const { push } = useToast();
  const products = useQuery({ queryKey: ['inventario', search, estado, categoria, page], queryFn: () => inventarioApi.productos(search, estado, categoria, page) });
  const categories = useQuery({ queryKey: ['inventario-categorias'], queryFn: inventarioApi.categorias });
  const movements = useQuery({ queryKey: ['movimientos', selected?.id], queryFn: () => inventarioApi.movimientos(selected!.id), enabled: !!selected });
  const form = useForm<ProductoForm>({ defaultValues: { referencia: '', nombre: '', categoria: '', precio_venta: 0, stock_minimo: 0 } });
  const categoryForm = useForm<{ nombre: string }>({ defaultValues: { nombre: '' } });
  const saveCategory = useMutation({ mutationFn: inventarioApi.crearCategoria, onSuccess: category => { void qc.invalidateQueries({ queryKey: ['inventario-categorias'] }); categoryForm.reset(); setCategoryOpen(false); push({ type: 'success', title: 'Categoría creada', message: `${category.nombre} ya está disponible para los productos.` }); }, onError: () => push({ type: 'error', title: 'No se pudo crear la categoría', message: 'Puede que ya exista una categoría con ese nombre. Verifica e inténtalo de nuevo.' }) });
  const saveProduct = useMutation({ mutationFn: (data: ProductoForm) => edit ? inventarioApi.editarProducto(edit.id, { ...data, categoria: data.categoria || null }) : inventarioApi.crearProducto({ ...data, categoria: data.categoria || null }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['inventario'] }); setEdit(undefined); push({ type: 'success', title: 'Producto guardado', message: 'El inventario quedó actualizado.' }); }, onError: () => push({ type: 'error', title: 'No se pudo guardar', message: 'Revisa la referencia y vuelve a intentarlo.' }) });
  const adjustMutation = useMutation({ mutationFn: () => inventarioApi.ajuste({ producto: adjust!.id, ...adjustForm }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['inventario'] }); setAdjust(null); push({ type: 'success', title: 'Ajuste registrado', message: 'Se creó el movimiento de inventario.' }); }, onError: () => push({ type: 'error', title: 'Ajuste rechazado', message: 'Revisa la cantidad, el motivo y el stock disponible.' }) });
  const productsByState = useMemo(() => products.data?.results ?? [], [products.data]);
  const openEdit = (product?: Producto) => { form.reset(product ? { referencia: product.referencia, nombre: product.nombre, categoria: product.categoria ? String(product.categoria) : '', precio_venta: Number(product.precio_venta), stock_minimo: Number(product.stock_minimo) } : { referencia: '', nombre: '', categoria: '', precio_venta: 0, stock_minimo: 0 }); setEdit(product ?? null); };
  const submitProduct = form.handleSubmit(values => { const parsed = productoSchema.safeParse(values); if (!parsed.success) { push({ type: 'error', title: 'Datos inválidos', message: parsed.error.issues[0]?.message ?? 'Revisa los campos.' }); return; } saveProduct.mutate(parsed.data); });
  const submitCategory = categoryForm.handleSubmit(values => { const parsed = categoriaSchema.safeParse(values); if (!parsed.success) { push({ type: 'error', title: 'Nombre inválido', message: parsed.error.issues[0]?.message ?? 'Revisa el nombre.' }); return; } saveCategory.mutate(parsed.data); });
  return <main className="jg-page inventory-page">
    <header className="inventory-page__heading"><div><span className="jg-eyebrow">OPERACIÓN</span><h1>Inventario de venta</h1><p>Productos, existencias y movimientos del negocio.</p></div>{user?.role === 'ADMIN' && <div className="inventory-page__actions"><Button onClick={() => { categoryForm.reset(); setCategoryOpen(true); }}>Nueva categoría</Button><Button variant="primary" onClick={() => openEdit()}><PackagePlus size={17}/> Nuevo producto</Button></div>}</header>
    <section className="inventory-toolbar" aria-label="Filtros de inventario"><label className="inventory-search"><Search size={17}/><Input aria-label="Buscar por referencia o nombre" placeholder="Buscar referencia o producto" value={search} onChange={e => {setSearch(e.target.value); setPage(1);}}/></label><label className="inventory-filter"><SlidersHorizontal size={16}/><Select aria-label="Filtrar categoría" value={categoria} onChange={e => {setCategoria(e.target.value);setPage(1);}}><option value="">Todas las categorías</option>{categories.data?.results.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</Select><Select aria-label="Filtrar estado de stock" value={estado} onChange={e => {setEstado(e.target.value);setPage(1);}}><option value="">Todos los estados</option><option value="ok">Stock disponible</option><option value="bajo">Stock bajo</option><option value="agotado">Agotados</option></Select></label></section>
    {products.isLoading ? <div className="inventory-skeleton">{[1,2,3,4].map(n => <Skeleton key={n} className="inventory-skeleton__row"/>)}</div> : products.isError ? <EmptyState title="No se pudo cargar el inventario" description="Comprueba tu conexión y vuelve a intentarlo." action={<Button onClick={() => void products.refetch()}>Reintentar</Button>}/> : !productsByState.length ? <EmptyState title="No hay productos" description="Cambia los filtros o crea el primer producto de venta." action={user?.role === 'ADMIN' ? <Button variant="primary" onClick={() => openEdit()}>Crear producto</Button> : undefined}/> : <><div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>Referencia</th><th>Producto</th><th>Existencia</th><th>Estado</th><th>Precio venta</th>{user?.role === 'ADMIN' && <th>Costo promedio</th>}<th>Acciones</th></tr></thead><tbody>{productsByState.map(p => <tr key={p.id}><td className="inventory-table__ref">{p.referencia}</td><td>{p.nombre}</td><td>{p.stock_actual}</td><td><Badge tone={p.estado_stock === 'ok' ? 'success' : p.estado_stock === 'bajo' ? 'warning' : 'danger'}><span className={p.estado_stock === 'ok' ? '' : 'inventory-pulse'} />{p.estado_stock === 'ok' ? 'Disponible' : p.estado_stock === 'bajo' ? 'Stock bajo' : 'Agotado'}</Badge></td><td>{cop.format(Number(p.precio_venta))}</td>{user?.role === 'ADMIN' && <td>{cop.format(Number(p.costo_promedio ?? 0))}</td>}<td className="inventory-table__actions"><Button aria-label={`Ver movimientos de ${p.nombre}`} onClick={() => setSelected(p)}><Eye size={16}/> Movimientos</Button>{user?.role === 'ADMIN' && <><Button onClick={() => openEdit(p)}>Editar</Button><Button onClick={() => { setAdjust(p); setAdjustForm({ cantidad: '', direccion: 'ENTRADA', motivo: '' }); }}>Ajustar</Button></>}</td></tr>)}</tbody></table></div><Pagination page={page} pages={Math.max(1, Math.ceil((products.data?.count ?? 0) / 25))} onChange={setPage}/></>}
    {edit !== undefined && <Drawer title={edit ? 'Editar producto' : 'Nuevo producto'} onClose={() => setEdit(undefined)}><form className="inventory-form" onSubmit={submitProduct}><label>Referencia<Input {...form.register('referencia')}/>{form.formState.errors.referencia && <small>{form.formState.errors.referencia.message}</small>}</label><label>Nombre<Input {...form.register('nombre')}/>{form.formState.errors.nombre && <small>{form.formState.errors.nombre.message}</small>}</label><label>Categoría<Select {...form.register('categoria')}><option value="">Sin categoría</option>{categories.data?.results.map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</Select></label><label>Precio de venta (COP)<Input type="number" min="0" step="0.01" {...form.register('precio_venta')}/></label><label>Stock mínimo<Input type="number" min="0" step="0.01" {...form.register('stock_minimo')}/></label><footer><Button type="button" onClick={() => setEdit(undefined)}>Cancelar</Button><Button variant="primary" type="submit" disabled={saveProduct.isPending}>{saveProduct.isPending ? 'Guardando…' : 'Guardar producto'}</Button></footer></form></Drawer>}
    {categoryOpen && <Drawer title="Nueva categoría" onClose={() => setCategoryOpen(false)}><form className="inventory-form" onSubmit={submitCategory}><p>Crea una categoría para organizar tus productos de venta.</p><label>Nombre de la categoría<Input autoFocus maxLength={100} placeholder="Ej. Herramientas eléctricas" {...categoryForm.register('nombre')}/>{categoryForm.formState.errors.nombre && <small>{categoryForm.formState.errors.nombre.message}</small>}</label><footer><Button type="button" onClick={() => setCategoryOpen(false)}>Cancelar</Button><Button variant="primary" type="submit" disabled={saveCategory.isPending}>{saveCategory.isPending ? 'Creando…' : 'Crear categoría'}</Button></footer></form></Drawer>}
    {selected && <Drawer title={`Movimientos · ${selected.referencia}`} onClose={() => setSelected(null)}>{movements.isLoading ? <Skeleton className="inventory-skeleton__row"/> : movements.isError ? <p role="alert">No fue posible cargar los movimientos.</p> : movements.data?.results.length ? <ul className="inventory-movements">{movements.data.results.map(m => <li key={m.id}><b>{m.tipo.replaceAll('_', ' ')}</b><span>{m.direccion === 'ENTRADA' ? '+' : '−'}{m.cantidad}</span><small>{new Date(m.creado_en).toLocaleString('es-CO')} · {m.motivo || 'Sin motivo'}</small></li>)}</ul> : <EmptyState title="Sin movimientos" description="Las compras y ajustes aparecerán aquí."/>}</Drawer>}
    {adjust && <Drawer title={`Ajustar · ${adjust.referencia}`} onClose={() => setAdjust(null)}><form className="inventory-form" onSubmit={e => { e.preventDefault(); if (!adjustForm.motivo.trim() || Number(adjustForm.cantidad) <= 0) { push({ type: 'error', title: 'Completa el ajuste', message: 'Indica una cantidad y un motivo.' }); return; } if (!window.confirm(`¿Confirmas el ajuste de ${adjustForm.cantidad} unidades?`)) return; adjustMutation.mutate(); }}><p>Existencia actual: <b>{adjust.stock_actual}</b></p><label>Movimiento<Select value={adjustForm.direccion} onChange={e => setAdjustForm({...adjustForm, direccion:e.target.value})}><option value="ENTRADA">Entrada</option><option value="SALIDA">Salida</option></Select></label><label>Cantidad<Input required min="0.01" step="0.01" type="number" value={adjustForm.cantidad} onChange={e => setAdjustForm({...adjustForm,cantidad:e.target.value})}/></label><label>Motivo<Input required maxLength={255} value={adjustForm.motivo} onChange={e => setAdjustForm({...adjustForm,motivo:e.target.value})}/></label><footer><Button type="button" onClick={() => setAdjust(null)}>Cancelar</Button><Button variant="primary" type="submit" disabled={adjustMutation.isPending}>Confirmar ajuste</Button></footer></form></Drawer>}
  </main>;
}
