# Generated by Django 5.2.18 on 2026-10-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gastos',
            },
        ),
        migrations.CreateModel(
            name='CompraInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveBigIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Compra de inventario',
                'verbose_name_plural': 'Compras de inventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='finanzas.comprainventario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventario.productoventa')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compra',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('ADDI', 'Addi'), ('SISTECREDITO', 'Sistecrédito')], max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='finanzas.categoriagasto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='cajas.turnocaja')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.AddConstraint(
            model_name='categoriagasto',
            constraint=models.UniqueConstraint(fields=('negocio', 'nombre'), name='uq_categoria_gasto_negocio'),
        ),
        migrations.AddIndex(
            model_name='comprainventario',
            index=models.Index(fields=['negocio', 'fecha'], name='finanzas_co_negocio_ebfeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='comprainventario',
            index=models.Index(fields=['negocio', 'proveedor'], name='finanzas_co_negocio_1196a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='comprainventario',
            constraint=models.UniqueConstraint(fields=('negocio', 'numero'), name='uq_compra_numero_negocio'),
        ),
        migrations.AddConstraint(
            model_name='comprainventario',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_compra_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_det_compra_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('costo_unitario__gte', 0)), name='ck_det_compra_costo_gte_0'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['negocio', 'fecha'], name='finanzas_ga_negocio_4f6542_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['negocio', 'categoria'], name='finanzas_ga_negocio_0389f7_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['negocio', 'medio_pago'], name='finanzas_ga_negocio_45a5b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='gasto',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ck_gasto_valor_gt_0'),
        ),
    ]
