# Generated by Django 5.2.18 on 2026-10-07 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finanzas', '0002_comprainventario_anulada_detallecompra_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaLeida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(max_length=160)),
                ('leida_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_leidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta leída',
                'verbose_name_plural': 'Alertas leídas',
                'constraints': [models.UniqueConstraint(fields=('negocio', 'usuario', 'clave'), name='uq_alerta_leida_usuario_clave')],
            },
        ),
    ]
