# Generated by Django 5.2.18 on 2026-10-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('referencia', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=180)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoriaproducto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
            ],
            options={
                'verbose_name': 'Producto de venta',
                'verbose_name_plural': 'Productos de venta',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por compra'), ('SALIDA_VENTA', 'Salida por venta'), ('SEPARADO', 'Reserva por separado'), ('CANCELACION_SEPARADO', 'Cancelación de separado'), ('DEVOLUCION', 'Devolución'), ('AJUSTE', 'Ajuste')], max_length=30)),
                ('direccion', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('origen_tipo', models.CharField(blank=True, max_length=50)),
                ('origen_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.productoventa')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
            },
        ),
        migrations.AddConstraint(
            model_name='categoriaproducto',
            constraint=models.UniqueConstraint(fields=('negocio', 'nombre'), name='uq_categoria_producto_negocio'),
        ),
        migrations.AddIndex(
            model_name='productoventa',
            index=models.Index(fields=['negocio', 'referencia'], name='inventario__negocio_25b6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='productoventa',
            index=models.Index(fields=['negocio', 'activo'], name='inventario__negocio_bdd01c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoventa',
            constraint=models.UniqueConstraint(fields=('negocio', 'referencia'), name='uq_producto_venta_referencia_negocio'),
        ),
        migrations.AddConstraint(
            model_name='productoventa',
            constraint=models.CheckConstraint(condition=models.Q(('costo_promedio__gte', 0)), name='ck_producto_costo_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productoventa',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gte', 0)), name='ck_producto_precio_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productoventa',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='ck_producto_stock_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productoventa',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='ck_producto_stock_minimo_gte_0'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['negocio', 'producto', '-creado_en'], name='inventario__negocio_ad315b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['negocio', 'tipo'], name='inventario__negocio_903a99_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['origen_tipo', 'origen_id'], name='inventario__origen__930dbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_mov_inv_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('costo_unitario__gte', 0)), name='ck_mov_inv_costo_gte_0'),
        ),
    ]
