import { useEffect, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes } from 'react';
import { createPortal } from 'react-dom';
import { X } from 'lucide-react';

export function Button({ variant = 'secondary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'danger' }) {
  return <button className={`jg-button jg-button--${variant} ${className}`.trim()} {...props} />;
}
export function Input({ className = '', ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={`jg-input ${className}`.trim()} {...props} />; }
export function Select({ className = '', children, ...props }: SelectHTMLAttributes<HTMLSelectElement>) { return <select className={`jg-select ${className}`.trim()} {...props}>{children}</select>; }
export function Badge({ tone = 'neutral', children }: { tone?: 'neutral' | 'success' | 'warning' | 'danger' | 'info'; children: ReactNode }) { return <span className={`jg-badge jg-badge--${tone}`}>{children}</span>; }
export function Card({ className = '', children }: { className?: string; children: ReactNode }) { return <section className={`jg-card ${className}`.trim()}>{children}</section>; }
export function Skeleton({ className = '' }: { className?: string }) { return <span aria-hidden="true" className={`jg-skeleton ${className}`.trim()} />; }
export function Spinner({ label = 'Cargando' }: { label?: string }) { return <span className="jg-spinner" role="status"><i /><span className="jg-sr-only">{label}</span></span>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="jg-empty"><span className="jg-empty__art" aria-hidden="true">⌕</span><h2>{title}</h2><p>{description}</p>{action}</div>; }

function useEscape(onClose: () => void) { useEffect(() => { const handle = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', handle); return () => window.removeEventListener('keydown', handle); }, [onClose]); }
export function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { useEscape(onClose); return createPortal(<div className="jg-modal__backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="jg-modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="jg-icon-button" aria-label="Cerrar" onClick={onClose}><X size={19} /></button></header><div className="jg-modal__body">{children}</div></section></div>, document.body); }
export function Drawer({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { useEscape(onClose); return createPortal(<div className="jg-drawer__backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="jg-drawer" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="jg-icon-button" aria-label="Cerrar" onClick={onClose}><X size={19} /></button></header><div className="jg-drawer__body">{children}</div></section></div>, document.body); }
export function ConfirmDialog({ title, message, confirmLabel = 'Confirmar', onCancel, onConfirm }: { title: string; message: string; confirmLabel?: string; onCancel: () => void; onConfirm: () => void }) { return <Modal title={title} onClose={onCancel}><p className="jg-confirm__message">{message}</p><footer className="jg-confirm__actions"><Button onClick={onCancel}>Cancelar</Button><Button variant="danger" onClick={onConfirm}>{confirmLabel}</Button></footer></Modal>; }
export function Pagination({ page, pages, onChange }: { page: number; pages: number; onChange: (page: number) => void }) { return <nav className="jg-pagination" aria-label="Paginación"><Button disabled={page <= 1} onClick={() => onChange(page - 1)}>Anterior</Button><span>Página {page} de {pages}</span><Button disabled={page >= pages} onClick={() => onChange(page + 1)}>Siguiente</Button></nav>; }
export function Tabs({ items, value, onChange }: { items: { id: string; label: string }[]; value: string; onChange: (id: string) => void }) { return <div className="jg-tabs" role="tablist">{items.map(item => <button key={item.id} className={`jg-tabs__tab${item.id === value ? ' jg-tabs__tab--active' : ''}`} role="tab" aria-selected={item.id === value} onClick={() => onChange(item.id)}>{item.label}</button>)}</div>; }
