# Generated by Django 5.2.18 on 2026-10-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_prevista_devolucion', models.DateTimeField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO_PARCIAL', 'Devuelto parcial'), ('FINALIZADO', 'Finalizado'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20)),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
            },
        ),
        migrations.CreateModel(
            name='ArticuloAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('referencia', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('ANDAMIO', 'Andamio'), ('HERRAMIENTA', 'Herramienta'), ('OTRO', 'Otro')], max_length=15)),
                ('cantidad_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_diario', models.DecimalField(decimal_places=2, default=0, help_text='Costo interno estimado por día para reportar margen de alquiler.', max_digits=14)),
                ('valor_reposicion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Artículo de alquiler',
                'verbose_name_plural': 'Artículos de alquiler',
            },
        ),
        migrations.CreateModel(
            name='DetalleAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tarifa_dia', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Detalle de alquiler',
                'verbose_name_plural': 'Detalles de alquiler',
            },
        ),
    ]
