# Generated by Django 5.2.18 on 2026-10-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio'),
        ),
        migrations.AddField(
            model_name='articuloalquiler',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articuloalquiler',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio'),
        ),
        migrations.AddField(
            model_name='detallealquiler',
            name='alquiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='alquileres.alquiler'),
        ),
        migrations.AddField(
            model_name='detallealquiler',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_alquiler', to='alquileres.articuloalquiler'),
        ),
        migrations.AddField(
            model_name='detallealquiler',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallealquiler',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio'),
        ),
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['negocio', 'fecha_prevista_devolucion'], name='alquileres__negocio_7cb05a_idx'),
        ),
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['negocio', 'cliente'], name='alquileres__negocio_010219_idx'),
        ),
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['negocio', 'estado'], name='alquileres__negocio_b6ae9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='alquiler',
            constraint=models.CheckConstraint(condition=models.Q(('deposito__gte', 0)), name='ck_alquiler_deposito_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='alquiler',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_alquiler_total_gte_0'),
        ),
        migrations.AddIndex(
            model_name='articuloalquiler',
            index=models.Index(fields=['negocio', 'referencia'], name='alquileres__negocio_353447_idx'),
        ),
        migrations.AddIndex(
            model_name='articuloalquiler',
            index=models.Index(fields=['negocio', 'tipo'], name='alquileres__negocio_ac1926_idx'),
        ),
        migrations.AddConstraint(
            model_name='articuloalquiler',
            constraint=models.UniqueConstraint(fields=('negocio', 'referencia'), name='uq_articulo_alquiler_referencia_negocio'),
        ),
        migrations.AddConstraint(
            model_name='articuloalquiler',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_total__gte', 0)), name='ck_alq_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='articuloalquiler',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible__gte', 0)), name='ck_alq_disp_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='articuloalquiler',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible__lte', models.F('cantidad_total'))), name='ck_alq_disp_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='articuloalquiler',
            constraint=models.CheckConstraint(condition=models.Q(('tarifa_diaria__gte', 0)), name='ck_alq_tarifa_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='articuloalquiler',
            constraint=models.CheckConstraint(condition=models.Q(('costo_diario__gte', 0)), name='ck_alq_costo_diario_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='articuloalquiler',
            constraint=models.CheckConstraint(condition=models.Q(('valor_reposicion__gte', 0)), name='ck_alq_reposicion_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallealquiler',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_det_alq_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='detallealquiler',
            constraint=models.CheckConstraint(condition=models.Q(('tarifa_dia__gte', 0)), name='ck_det_alq_tarifa_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallealquiler',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_devuelta__gte', 0)), name='ck_det_alq_devuelta_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallealquiler',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_devuelta__lte', models.F('cantidad'))), name='ck_det_alq_devuelta_lte_cantidad'),
        ),
    ]
