# Generated by Django 5.2.18 on 2026-10-07 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='alquileres.detallealquiler')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
            ],
            options={
                'verbose_name': 'Devolución de alquiler',
                'verbose_name_plural': 'Devoluciones de alquiler',
                'indexes': [models.Index(fields=['negocio', 'fecha'], name='alquileres__negocio_260a8d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_dev_alq_cantidad_gt_0'), models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='ck_dev_alq_valor_gte_0')],
            },
        ),
    ]
