# Generated by Django 5.2.18 on 2026-10-07 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0003_devolucionalquiler'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventarioAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('INICIAL', 'Existencia inicial')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='alquileres.articuloalquiler')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario de alquiler',
                'verbose_name_plural': 'Movimientos de inventario de alquiler',
                'indexes': [models.Index(fields=['negocio', 'articulo', '-creado_en'], name='alquileres__negocio_c5d8da_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_mov_alquiler_cantidad_gt_0')],
            },
        ),
    ]
