# Generated by Django 5.2.18 on 2026-10-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0002_initial'),
        ('cajas', '0001_initial'),
        ('core', '0001_initial'),
        ('finanzas', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caja',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='abono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='ventas.abono'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='finanzas.gasto'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='alquileres.alquiler'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibos_caja', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='recibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='cajas.recibocaja'),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='cajas.caja'),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.negocio'),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='cajas.turnocaja'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cajas.turnocaja'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('negocio', 'nombre'), name='uq_caja_nombre_negocio'),
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['negocio', 'estado'], name='cajas_turno_negocio_c52b33_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['negocio', 'apertura_en'], name='cajas_turno_negocio_d541ee_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['negocio', 'usuario'], name='cajas_turno_negocio_750606_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.CheckConstraint(condition=models.Q(('base_inicial__gte', 0)), name='ck_turno_base_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.CheckConstraint(condition=models.Q(('efectivo_contado__gte', 0)), name='ck_turno_contado_gte_0'),
        ),
        migrations.AddIndex(
            model_name='recibocaja',
            index=models.Index(fields=['negocio', 'fecha'], name='cajas_recib_negocio_e8dd83_idx'),
        ),
        migrations.AddIndex(
            model_name='recibocaja',
            index=models.Index(fields=['negocio', 'cliente'], name='cajas_recib_negocio_682bc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='recibocaja',
            constraint=models.UniqueConstraint(fields=('negocio', 'numero'), name='uq_recibo_numero_negocio'),
        ),
        migrations.AddConstraint(
            model_name='recibocaja',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ck_recibo_valor_gt_0'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['negocio', 'turno', 'tipo'], name='cajas_movim_negocio_98b299_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['negocio', 'medio_pago'], name='cajas_movim_negocio_bd3151_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['negocio', 'creado_en'], name='cajas_movim_negocio_0be944_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ck_mov_caja_valor_gt_0'),
        ),
    ]
