# Generated by Django 5.2.18 on 2026-10-07 18:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='preferencias_notificaciones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=10),
        ),
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(blank=True, default='', max_length=150)),
                ('razon_social', models.CharField(blank=True, default='', max_length=200)),
                ('nit', models.CharField(blank=True, default='', max_length=30)),
                ('direccion', models.CharField(blank=True, default='', max_length=250)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos-negocio/')),
                ('efectivo_habilitado', models.BooleanField(default=True)),
                ('transferencia_habilitada', models.BooleanField(default=True)),
                ('addi_habilitado', models.BooleanField(default=True)),
                ('sistecredito_habilitado', models.BooleanField(default=True)),
                ('alquiler_recargo_diario_multiplicador', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('alquiler_horas_anticipacion_avisar_vencer', models.PositiveIntegerField(default=24)),
                ('separado_politica_cancelacion', models.CharField(choices=[('DEVOLVER_TODO', 'Devolver todo'), ('RETENER_PORCENTAJE', 'Retener porcentaje')], default='DEVOLVER_TODO', max_length=30)),
                ('separado_porcentaje_retencion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('credito_cupo_por_defecto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('inventario_stock_minimo_por_defecto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('recibos_prefijo_numeracion', models.CharField(blank=True, default='', max_length=10)),
                ('recibos_condiciones_alquiler', models.TextField(blank=True, default='')),
                ('recibos_pie_pagina', models.TextField(blank=True, default='')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracion', to='core.negocio')),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
                'verbose_name_plural': 'Configuraciones del negocio',
            },
        ),
    ]
